title: Service
preset: page

status:
  draft:
    label: Draft
    text:
      de: Der Artikel ist noch im Entwurfsstatus und wird nicht auf der Webseite angezeigt.
      en: The article is still in draft mode and is not shown on the website.
  listed:
    label: Published
    text:
      de: Der Artikel ist veröffentlicht und wird auf der Webseite dargestellt.
      en: The article is published and viewable on the website.

fields:
  headline:
    type: text
    width: 3/4
    required: true
  text:
    type: textarea
    size: medium

sidebar:
  cover:
    type: files
    label: Cover
    layout: cards
    info: "{{ file.dimensions }}"
    template: cover
    min: 0
    max: 1