title: Leistungen
extends: layouts/services
icon: ⚓️

drafts:
  extends: sections/services
  label: Leistungen (Entwurf)

listed:
  extends: sections/services
  label: Leistungen (Veröffentlicht)
  layout: cardlets