title: Leistungsbeschreibung
preset: page

status:
  draft:
    label: Entwurf
    text: Der Artikel ist noch im Entwurfsstatus und wird nicht auf der Webseite angezeigt.
  listed:
    label: Veröffentlicht
    text: Der Artikel ist veröffentlicht und wird auf der Webseite dargestellt.

fields:
  headline:
    type: text
    width: 3/4
    required: true
  text:
    type: textarea
    size: medium

sidebar:
  cover:
    type: files
    label: Cover
    layout: cards
    info: "{{ file.dimensions }}"
    template: cover
    min: 0
    max: 1